name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: npm i
      - run: npm i
        working-directory: projects/ngx-markjs
      - run: npm run build
        working-directory: projects/ngx-markjs
      - run: npm audit signatures
        working-directory: projects/ngx-markjs
      - name: Release
        run: npx semantic-release
        working-directory: projects/ngx-markjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}




